services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simplebank-api
    working_dir: /app
    command: ["/app/main"]
    environment:
      DB_SOURCE: "postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable"
    depends_on:
      - postgres
    ports:
      - "8080:8080"
