name: Build Image

on:
  workflow_run:
    workflows: ["Run unit tests"]
    types:
      - completed

jobs:
  build:
    name: Build image
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_REPOSITORY: my-simplebank
      IMAGE_TAG: ${{ github.event.workflow_run.head_sha }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image to DockerHub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ github.ref_name == 'main' && 'main' || github.ref_name == 'dev' && 'dev' || 'ci' }}
